#!/bin/sh
# Host-side test for the XPRS codec: converts aurora's test/xprs_corpus.json
# (the same 205 spec examples test/xprs_packet_test.dart replays) into a C
# include, builds xprs.c + test_xprs_host.c with gcc, and runs it.
set -e
cd "$(dirname "$0")"

CORPUS=../../../test/xprs_corpus.json
OUT=xprs_corpus_inc.h

python3 - "$CORPUS" > "$OUT" <<'EOF'
import json, sys
d = json.load(open(sys.argv[1]))
def esc(s):
    out = []
    for ch in s.encode():
        if ch in (0x22, 0x5C):        # " and backslash
            out.append('\\' + chr(ch))
        elif 0x20 <= ch <= 0x7E:
            out.append(chr(ch))
        else:
            out.append('\\%03o' % ch)
    return ''.join(out)
print('/* generated by test_xprs_host.sh from test/xprs_corpus.json */')
print('static const corpus_t g_corpus[] = {')
for e in d:
    print('  { "%s", %d, "%s" },' % (esc(e['wire']), e['bytes'] or -1, e['id']))
print('};')
EOF

gcc -Wall -Wextra -Werror -O1 -o /tmp/test_xprs xprs.c test_xprs_host.c
/tmp/test_xprs
